version: "2"
services:
  bus:
    build:
      context: ./bus
      dockerfile: bus.dockerfile
    depends_on:
      - mongo
    links: 
      - mongo

  news:
    build:
      context: ./news
      dockerfile: news.dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links: 
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - database:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    links: 
      - mongo
      
volumes:
  database: {}